### ISSUE TITLE
HTTPHandler should be renamed HTTPHandlerFunc

### ISSUE THREAD

**Issue by jlovison** [deferpanic/deferclient#41]
HTTPHandler is not work with a `http.Handler` interface, but rather a `http.HandlerFunc` interface. Should be renamed for clarity.

**Comment by jlovison** [comment]
Also, as the argument and return value both conform to the `http.HandlerFunc` definition, probably best to just use that type for both. Such as:

     func (c *Client) HTTPHandler(f http.HandlerFunc) http.HandlerFunc {

**Comment by eyberg** [comment]
https://github.com/deferpanic/deferclient/pull/43
