### ISSUE TITLE
lsof should be listed as a dependency

### ISSUE THREAD

**Issue by jlovison** [deferpanic/deferclient#42]
I was getting status 127 errors when running after adding deferstats, and had to decipher that the official golang docker container I was building on top of didn't include lsof.

Even though it's fairly universal on linux boxes, it should probably still be mentioned as a dependency for deferstats.

**Comment by eyberg** [comment]
for sure, that or I'm open to just removing it and using platform specific ways of accomplishing the same thing - it's a new dependency

**Comment by jlovison** [comment]
Given the prevelancy of the docker use case for golang apps, dropping the dependency is probably the better approach.

**Comment by eyberg** [comment]
https://github.com/deferpanic/deferclient/pull/43
