### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by anweiss** [deferpanic/deferclient#45]
No `SetTotal` method assigned to the `mem` type for Windows. Prevents users from collecting data from applications running on Windows

**Comment by eyberg** [comment]
just to track -- file cnt support does not exist either

**Comment by anweiss** [comment]
Indeed...will try and submit a PR

**Comment by anweiss** [comment]
@ahmetalpbalkan ...wanna help out?

**Comment by eyberg** [comment]
threw in some stubs for now to allow compilation

**Comment by eyberg** [comment]
https://github.com/deferpanic/deferclient/pull/52 && https://github.com/deferpanic/deferclient/pull/54 should address file count && total memory respectively
