### ISSUE TITLE
Allow the client to take http.Handler

### ISSUE THREAD

**Issue by pspeter3** [deferpanic/deferclient#49]
Right now the client only supports `http.HandlerFunc`. The more generic interface for Go is the `http.Handler` which is the interface that supports `ServeHTTP`. Instead of requiring HandlerFunc, it would be nice if the code accepted the `http.Handler` interface instead.

**Comment by eyberg** [comment]
something like this? https://github.com/deferpanic/deferclient/pull/51

**Comment by pspeter3** [comment]
Yeah, though I'm surprised the code between the `http.Handler` and `http.HandlerFunc` are not shared since you can turn a `http.HandlerFunc` into an `http.Handler`

**Comment by eyberg** [comment]
for sure - just seeing if that was the right direction

**Comment by eyberg** [comment]
cc @pspeter3 https://github.com/deferpanic/deferclient/pull/51

**Comment by chrsm** [comment]
This would be a fantastic addition, :+1: on getting #51 merged.

**Comment by eyberg** [comment]
merged
