### ISSUE TITLE
Process File Count on Windows

### ISSUE THREAD

**Issue by anweiss** [deferpanic/deferclient#50]
In reference to #45, the `openFileCnt` function is much more complex to implement on Windows due to the nature by which open process handles can be retrieved. I am by no means a low-level systems developer, but typically one could use the [Handle](https://technet.microsoft.com/en-us/sysinternals/bb896655.aspx) utility to get this information. However, this tool is not redistributable. 

Because of this, we may want to rethink or come up with a better approach to this function, or simply return an instance of `Client` with the `GetFd` field set to `false` on Windows for the time being.

Thoughts?

**Comment by eyberg** [comment]
I found this in a cgo test -> 

https://github.com/golang/go/blob/master/misc/cgo/test/issue8517_windows.go#L18-L31
https://msdn.microsoft.com/en-us/library/windows/desktop/ms683214(v=vs.85).aspx

if you want to take a crack at it lmk - otherwise I can prob. get to it sometime nxt wk

**Comment by anweiss** [comment]
Good find! Although, not sure how to implement it with `os.Getpid()`. In the test, it looks like they're casting 0 as a `uintptr` and grabbing its bitwise complement. Does `current_process` refer to the execution context of the test itself?

If I try to set `const current_process = ^uintptr(os.Getpid())` and then pass this value in to the `getProcessHandleCount` call, it fails with a `handle is invalid` error.

**Comment by eyberg** [comment]
the syscall takes a process handle not the id - I dl'd process explorer and it seems to match up - does this work for you ? https://github.com/deferpanic/deferclient/pull/52

**Comment by anweiss** [comment]
ah, perfect! makes sense. I knew it took a handle, but just couldn't figure out the right construct to make it work....lgtm!

**Comment by eyberg** [comment]
initial support from https://github.com/deferpanic/deferclient/pull/52
