### ISSUE TITLE
in china Cannot access     

### ISSUE THREAD

**Issue by gobet8** [deferpanic/deferclient#72]
in china Cannot access     .......GWF......GWFscreen.....

**Comment by eyberg** [comment]
eh.. yeh sorry - we've had spottiness varying on location from places there - some cities are fine, some are not - if you want we'd be more than happy to update the wiki/readme with instructions on the easiest/best way of defeating it

fwiw - in Go - the best way to specify a proxy that I know of is through an ENV variable

```
export HTTP_PROXY="https://my_proxy.com:1234" ./my_app
```
