### ISSUE TITLE
Make it possible to use custom header for tracing across microservices

### ISSUE THREAD

**Issue by raphael** [deferpanic/deferclient#73]
We already use the "X-Request-ID" header to do that, would be nice not to have to add a new header (X-dpparentspanid) to all requests.

**Comment by vsukhin** [comment]
We're planning to prepare integration middleware for you on Monday https://github.com/deferpanic/dpgoa I was thinking about preparing a special Recovery() middleware method for you based on your existing one and replacing internals with deferpanic.com integration. And I was planning to use your goa.Context for passing variables in chain of handlers. So, we could either add a new variable for you, or you can pass everything you want in your context structure. Recently we did integration for context.Context, this is how it looks like there https://github.com/deferpanic/dpcontext/blob/master/middleware/middleware.go

**Comment by eyberg** [comment]
@raphael I believe the x-request-id header (eg: heroku style) you are using is used for a slightly different purpose than how we are using dpParentSpanId

we track each request with 2 identifiers - one for any parent request and one for the one we are responding to - this allows us to implement dapper style tracing for those using micro-services - so it's less of identification and more for tracing - it's pretty explicitly defined unlike the heroku style that allows you to throw anything into it and doesn't tie them together

we can def. have an option to turn this feature off if you wish though

**Comment by raphael** [comment]
@vsukhin sounds great! I had taken a first pass at a deferpanic middleware for goa, see https://github.com/raphael/goa-middleware.

@eyberg thanks for the clarification, makes sense. We actually use `X-Request-ID` for tracing (I realize now I should have been more specific). If you take a look at the corresponding [goa middleware](https://github.com/raphael/goa/blob/master/middleware.go#L143-L158) you'll see that it tries to grab the ID from the incoming request and if there isn't one creates it. The idea is that the ID is then sent with any request made further down the line. I'm not familiar with how dapper does it - I'll take a look. Being able to turn off that feature might be helpful as we have standardized on `X-Request-ID` for all our systems - Go or not. Thanks!
